# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7291e5c614a330938bb8795eac50f50d1268b631748627ccee1a861d7611ac1914d5857db9025223042949e2136bded89172d71a1a17e328518449375a550561
  payonline_merchant_id: <%= ENV["PAYONLINE_MERCHANT_ID"] %>
  payonline_private_security_key: <%= ENV["PAYONLINE_PRIVATE_SECURITY_KEY"] %>
  payonline_return_url: <%= ENV["PAYONLINE_RETURN_URL"] %>
  payonline_fail_url: <%= ENV["PAYONLINE_FAIL_URL"] %>
  demo_phone_number: "+79991112233"
  demo_code: "1234"

test:
  secret_key_base: ff1f0c15c6bc79629695a083d474b95225fcdf979ebd34b9a1444a0d91a4b27d42e4e0f75c8a23f1d59878e9ccc811b40645ad6633654495c04967c4bbb420bd
  demo_phone_number: "+79991112233"
  demo_code: "1234"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sms_ru_api_id: <%= ENV["SMS_RU_API_ID"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_s3_bucket_name: <%= ENV["AWS_S3_BUCKET_NAME"] %>
  payonline_merchant_id: <%= ENV["PAYONLINE_MERCHANT_ID"] %>
  payonline_private_security_key: <%= ENV["PAYONLINE_PRIVATE_SECURITY_KEY"] %>
  payonline_return_url: <%= ENV["PAYONLINE_RETURN_URL"] %>
  payonline_fail_url: <%= ENV["PAYONLINE_FAIL_URL"] %>
  apn_certificate: "<%= ENV["APN_CERTIFICATE"] %>"
  apn_environment: <%= ENV["APN_ENVIRONMENT"] %>
  demo_phone_number: "<%= ENV["DEMO_PHONE_NUMBER"] %>"
  demo_code: "<%= ENV["DEMO_CODE"] %>"
  mailgun_domain: "<%= ENV["MAILGUN_DOMAIN"] %>"
